[global]
author=["snk-fpga"]

[parse]
sourcefile=[ "bbusters.cpp" ]
machines=[ "bbusters", "bbustersu", "bbustersua", "bbustersj", "bbustersja" ]
rename = [
    { setname="bbusters", name="Beast Busters (FF, SNK, 1989)" },
    { setname="bbustersu", name="Beast Busters (FF, SNK, 1989, US v3)" },
    { setname="bbustersua", name="Beast Busters (FF, SNK, 1989, US v2)" },
    { setname="bbustersj", name="Beast Busters (FF, SNK, 1989, Japan v2, 3P)" },
    { setname="bbustersja", name="Beast Busters (FF, SNK, 1989, Japan v2, 2P)" },
]

[buttons]
names=[
    { machine="bbusters", names="Disparo,Granada" },
    { machine="bbustersu", names="Disparo,Granada" },
    { machine="bbustersua", names="Disparo,Granada" },
    { machine="bbustersj", names="Disparo,Granada" },
    { machine="bbustersja", names="Disparo,Granada" }
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]

[ROM]

regions = [
    { name="maincpu", width=16, reverse=true },
    { name="audiocpu",             start="SND_START" },
    { name="tx_tiles",             start="JTFRAME_BA1_START" },
    { name="bg1_tiles",            start="BG1_START" },
    { name="bg2_tiles",            start="BG2_START" },
    { name="sprites1",             start="JTFRAME_BA2_START" },
    { name="sprites2",             start="JTFRAME_BA3_START" },
    { name="ymsnd:adpcma",         start="PCMA_START" },
    { name="ymsnd:adpcmb",         start="PCMB_START" },
    { name="sprites1:scale_table", start="JTFRAME_PROM_START", files=[ {name="bb-6.e7", crc="61f3de03", size=0x10000} ] },
    { name="sprites2:scale_table", skip=true },
]
order = [ "maincpu", "audiocpu", "tx_tiles", "bg1_tiles", "bg2_tiles", "sprites1", "sprites2",
          "ymsnd:adpcma", "ymsnd:adpcmb", "sprites1:scale_table" ]
